import React, { Component } from "react";
import OneWayFlightCard from "../SearchResults/GenericCard/oneWayFlightCard";

class OneWaySearchResult extends Component {
  state = {
    result: {
      responseMessage: [
        {
          value:
            "AirSearchModifiers@ExcludeGroundTransportation attribute is not supported for the requested provider.",
          code: 701372,
          type: "Warning",
          providerCode: "1G",
          supplierCode: null,
        },
        {
          value: " [ACH] Provider error: No Supported ACH carrier requested",
          code: 15058,
          type: "Error",
          providerCode: "ACH",
          supplierCode: null,
        },
      ],
      traceId: "8688a1c5-e940-45e1-816d-183058743d69",
      transactionId: "6384DAE40A0D6A8162041B27D8D75F9E",
      responseTime: 5973,
      commandHistory: null,
      brandList: null,
      currencyType: "USD",
      fareNoteList: null,
      routeList: {
        route: [
          {
            leg: [
              {
                legDetail: [],
                key: "1Xb7KhBqWDKA7shbBAAAAA==",
                group: 0,
                origin: "DAC",
                destination: "NYC",
              },
            ],
            key: "1Xb7KhBqWDKAethbBAAAAA==",
          },
        ],
      },
      alternateRouteList: null,
      fareInfoMessage: [],
      airPricingSolution: [],
      airPricePoints: [
        {
          airPricingInfo: [
            {
              fareInfo: [],
              fareStatus: null,
              fareInfoRef: [
                {
                  key: "1Xb7KhBqWDKAnshbBAAAAA==",
                },
              ],
              bookingInfo: [],
              taxInfo: [
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKApshbBAAAAA==",
                  category: "BD",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD6.00",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAqshbBAAAAA==",
                  category: "OW",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD36.00",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKArshbBAAAAA==",
                  category: "P7",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD10.00",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAsshbBAAAAA==",
                  category: "P8",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD10.00",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAtshbBAAAAA==",
                  category: "UT",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD48.00",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAushbBAAAAA==",
                  category: "TR",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD6.10",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAvshbBAAAAA==",
                  category: "US",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD19.10",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAwshbBAAAAA==",
                  category: "XA",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD3.96",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAxshbBAAAAA==",
                  category: "XY",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD7.00",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAyshbBAAAAA==",
                  category: "YC",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD5.99",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAzshbBAAAAA==",
                  category: "E5",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD3.90",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKA0shbBAAAAA==",
                  category: "YR",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD245.00",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
              ],
              fareCalc: "DAC TK X/IST TK NYC 365.00TF2PXOW NUC365.00END ROE1.0",
              passengerType: [
                {
                  name: null,
                  loyaltyCard: [],
                  discountCard: [],
                  personalGeography: null,
                  code: "ADT",
                  age: null,
                  dob: null,
                  gender: null,
                  pricePTCOnly: null,
                  bookingTravelerRef: null,
                  accompaniedPassenger: false,
                  residencyType: null,
                  fareGuaranteeInfo: null,
                },
              ],
              bookingTravelerRef: [],
              waiverCode: null,
              paymentRef: [],
              changePenalty: [
                {
                  amount: null,
                  percentage: "0.00",
                  penaltyApplies: "Anytime",
                  noShow: null,
                },
              ],
              cancelPenalty: [
                {
                  amount: "USD130.00",
                  percentage: null,
                  penaltyApplies: "Before Departure",
                  noShow: null,
                },
              ],
              noShowPenalty: [],
              mostRestrictivePenalties: null,
              feeInfo: [],
              adjustment: [],
              yield: [],
              airPricingModifiers: null,
              ticketingModifiersRef: [],
              airSegmentPricingModifiers: [],
              flightOptionsList: {
                flightOption: [
                  {
                    option: [
                      {
                        bookingInfo: [
                          {
                            bookingCode: "T",
                            bookingCount: "9",
                            cabinClass: "Economy",
                            fareInfoRef: "1Xb7KhBqWDKAnshbBAAAAA==",
                            segmentRef: "1Xb7KhBqWDKAdshbBAAAAA==",
                            couponRef: null,
                            airItinerarySolutionRef: null,
                            hostTokenRef: null,
                            taxInfoRef: null,
                          },
                          {
                            bookingCode: "T",
                            bookingCount: "9",
                            cabinClass: "Economy",
                            fareInfoRef: "1Xb7KhBqWDKAnshbBAAAAA==",
                            segmentRef: "1Xb7KhBqWDKAfshbBAAAAA==",
                            couponRef: null,
                            airItinerarySolutionRef: null,
                            hostTokenRef: null,
                            taxInfoRef: null,
                          },
                        ],
                        connection: [
                          {
                            fareNote: null,
                            changeOfPlane: false,
                            changeOfTerminal: false,
                            changeOfAirport: false,
                            stopOver: false,
                            minConnectionTime: null,
                            duration: null,
                            segmentIndex: 0,
                            flightDetailsIndex: null,
                            includeStopOverToFareQuote: null,
                          },
                        ],
                        key: "1Xb7KhBqWDKA1shbBAAAAA==",
                        travelTime: "P1DT2H5M0S",
                      },
                      {
                        bookingInfo: [
                          {
                            bookingCode: "T",
                            bookingCount: "9",
                            cabinClass: "Economy",
                            fareInfoRef: "1Xb7KhBqWDKAnshbBAAAAA==",
                            segmentRef: "1Xb7KhBqWDKAdshbBAAAAA==",
                            couponRef: null,
                            airItinerarySolutionRef: null,
                            hostTokenRef: null,
                            taxInfoRef: null,
                          },
                          {
                            bookingCode: "T",
                            bookingCount: "9",
                            cabinClass: "Economy",
                            fareInfoRef: "1Xb7KhBqWDKAnshbBAAAAA==",
                            segmentRef: "1Xb7KhBqWDKAhshbBAAAAA==",
                            couponRef: null,
                            airItinerarySolutionRef: null,
                            hostTokenRef: null,
                            taxInfoRef: null,
                          },
                        ],
                        connection: [
                          {
                            fareNote: null,
                            changeOfPlane: false,
                            changeOfTerminal: false,
                            changeOfAirport: false,
                            stopOver: false,
                            minConnectionTime: null,
                            duration: null,
                            segmentIndex: 0,
                            flightDetailsIndex: null,
                            includeStopOverToFareQuote: null,
                          },
                        ],
                        key: "1Xb7KhBqWDKA4shbBAAAAA==",
                        travelTime: "P1DT14H25M0S",
                      },
                    ],
                    legRef: "1Xb7KhBqWDKA7shbBAAAAA==",
                    origin: "DAC",
                    destination: "NYC",
                  },
                ],
              },
              baggageAllowances: null,
              fareRulesFilter: null,
              policyCodesList: null,
              priceChange: [],
              actionDetails: null,
              commission: [],
              origin: null,
              destination: null,
              key: "1Xb7KhBqWDKAoshbBAAAAA==",
              commandKey: null,
              amountType: null,
              includesVAT: null,
              exchangeAmount: null,
              forfeitAmount: null,
              refundable: true,
              exchangeable: null,
              latestTicketingTime: "2021-03-27T23:59:00.000+06:00",
              pricingMethod: "GUARANTEED",
              checksum: null,
              platingCarrier: "TK",
              providerReservationInfoRef: null,
              airPricingInfoGroup: null,
              totalNetPrice: null,
              ticketed: null,
              pricingType: null,
              trueLastDateToTicket: null,
              fareCalculationInd: null,
              cat35Indicator: false,
              providerCode: "1G",
              supplierCode: null,
              totalPrice: "USD766.05",
              basePrice: "USD365.00",
              approximateTotalPrice: "USD766.05",
              approximateBasePrice: "USD365.00",
              equivalentBasePrice: null,
              taxes: "USD401.05",
              fees: null,
              services: null,
              approximateTaxes: null,
              approximateFees: null,
              inPolicy: null,
              preferredOption: null,
              elStat: null,
              keyOverride: null,
              eticketability: "YES",
            },
          ],
          airPricingResultMessage: [],
          feeInfo: [],
          fareNote: [],
          taxInfo: [],
          key: "1Xb7KhBqWDKAfthbBAAAAA==",
          completeItinerary: true,
          totalPrice: "USD766.05",
          basePrice: "USD365.00",
          approximateTotalPrice: "USD766.05",
          approximateBasePrice: "USD365.00",
          equivalentBasePrice: null,
          taxes: "USD401.05",
          fees: null,
          services: null,
          approximateTaxes: "USD401.05",
          approximateFees: null,
        },
        {
          airPricingInfo: [
            {
              fareInfo: [],
              fareStatus: null,
              fareInfoRef: [
                {
                  key: "1Xb7KhBqWDKA8shbBAAAAA==",
                },
              ],
              bookingInfo: [],
              taxInfo: [
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKA+shbBAAAAA==",
                  category: "BD",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD6.00",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKA/shbBAAAAA==",
                  category: "OW",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD36.00",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAAthbBAAAAA==",
                  category: "P7",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD10.00",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKABthbBAAAAA==",
                  category: "P8",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD10.00",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKACthbBAAAAA==",
                  category: "UT",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD48.00",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKADthbBAAAAA==",
                  category: "TR",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD6.10",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAEthbBAAAAA==",
                  category: "US",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD19.10",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAFthbBAAAAA==",
                  category: "XA",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD3.96",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAGthbBAAAAA==",
                  category: "XY",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD7.00",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAHthbBAAAAA==",
                  category: "YC",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD5.99",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAIthbBAAAAA==",
                  category: "E5",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD3.90",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAJthbBAAAAA==",
                  category: "YR",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD245.00",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
              ],
              fareCalc: "DAC TK X/IST TK NYC 365.00TF2PXOW NUC365.00END ROE1.0",
              passengerType: [
                {
                  name: null,
                  loyaltyCard: [],
                  discountCard: [],
                  personalGeography: null,
                  code: "ADT",
                  age: null,
                  dob: null,
                  gender: null,
                  pricePTCOnly: null,
                  bookingTravelerRef: null,
                  accompaniedPassenger: false,
                  residencyType: null,
                  fareGuaranteeInfo: null,
                },
              ],
              bookingTravelerRef: [],
              waiverCode: null,
              paymentRef: [],
              changePenalty: [
                {
                  amount: null,
                  percentage: "0.00",
                  penaltyApplies: "Anytime",
                  noShow: null,
                },
              ],
              cancelPenalty: [
                {
                  amount: "USD130.00",
                  percentage: null,
                  penaltyApplies: "Before Departure",
                  noShow: null,
                },
              ],
              noShowPenalty: [],
              mostRestrictivePenalties: null,
              feeInfo: [],
              adjustment: [],
              yield: [],
              airPricingModifiers: null,
              ticketingModifiersRef: [],
              airSegmentPricingModifiers: [],
              flightOptionsList: {
                flightOption: [
                  {
                    option: [
                      {
                        bookingInfo: [
                          {
                            bookingCode: "T",
                            bookingCount: "9",
                            cabinClass: "Economy",
                            fareInfoRef: "1Xb7KhBqWDKA8shbBAAAAA==",
                            segmentRef: "1Xb7KhBqWDKAdshbBAAAAA==",
                            couponRef: null,
                            airItinerarySolutionRef: null,
                            hostTokenRef: null,
                            taxInfoRef: null,
                          },
                          {
                            bookingCode: "T",
                            bookingCount: "9",
                            cabinClass: "Economy",
                            fareInfoRef: "1Xb7KhBqWDKA8shbBAAAAA==",
                            segmentRef: "1Xb7KhBqWDKAjshbBAAAAA==",
                            couponRef: null,
                            airItinerarySolutionRef: null,
                            hostTokenRef: null,
                            taxInfoRef: null,
                          },
                        ],
                        connection: [
                          {
                            fareNote: null,
                            changeOfPlane: false,
                            changeOfTerminal: false,
                            changeOfAirport: false,
                            stopOver: false,
                            minConnectionTime: null,
                            duration: null,
                            segmentIndex: 0,
                            flightDetailsIndex: null,
                            includeStopOverToFareQuote: null,
                          },
                        ],
                        key: "1Xb7KhBqWDKAKthbBAAAAA==",
                        travelTime: "P1DT1H50M0S",
                      },
                    ],
                    legRef: "1Xb7KhBqWDKA7shbBAAAAA==",
                    origin: "DAC",
                    destination: "NYC",
                  },
                ],
              },
              baggageAllowances: null,
              fareRulesFilter: null,
              policyCodesList: null,
              priceChange: [],
              actionDetails: null,
              commission: [],
              origin: null,
              destination: null,
              key: "1Xb7KhBqWDKA9shbBAAAAA==",
              commandKey: null,
              amountType: null,
              includesVAT: null,
              exchangeAmount: null,
              forfeitAmount: null,
              refundable: true,
              exchangeable: null,
              latestTicketingTime: "2021-03-27T23:59:00.000+06:00",
              pricingMethod: "GUARANTEED",
              checksum: null,
              platingCarrier: "TK",
              providerReservationInfoRef: null,
              airPricingInfoGroup: null,
              totalNetPrice: null,
              ticketed: null,
              pricingType: null,
              trueLastDateToTicket: null,
              fareCalculationInd: null,
              cat35Indicator: false,
              providerCode: "1G",
              supplierCode: null,
              totalPrice: "USD766.05",
              basePrice: "USD365.00",
              approximateTotalPrice: "USD766.05",
              approximateBasePrice: "USD365.00",
              equivalentBasePrice: null,
              taxes: "USD401.05",
              fees: null,
              services: null,
              approximateTaxes: null,
              approximateFees: null,
              inPolicy: null,
              preferredOption: null,
              elStat: null,
              keyOverride: null,
              eticketability: "YES",
            },
          ],
          airPricingResultMessage: [],
          feeInfo: [],
          fareNote: [],
          taxInfo: [],
          key: "1Xb7KhBqWDKAgthbBAAAAA==",
          completeItinerary: true,
          totalPrice: "USD766.05",
          basePrice: "USD365.00",
          approximateTotalPrice: "USD766.05",
          approximateBasePrice: "USD365.00",
          equivalentBasePrice: null,
          taxes: "USD401.05",
          fees: null,
          services: null,
          approximateTaxes: "USD401.05",
          approximateFees: null,
        },
        {
          airPricingInfo: [
            {
              fareInfo: [],
              fareStatus: null,
              fareInfoRef: [
                {
                  key: "1Xb7KhBqWDKANthbBAAAAA==",
                },
              ],
              bookingInfo: [],
              taxInfo: [
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAPthbBAAAAA==",
                  category: "BD",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD6.00",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAQthbBAAAAA==",
                  category: "OW",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD36.00",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKARthbBAAAAA==",
                  category: "P7",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD10.00",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKASthbBAAAAA==",
                  category: "P8",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD10.00",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKATthbBAAAAA==",
                  category: "UT",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD48.00",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAUthbBAAAAA==",
                  category: "TR",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD6.10",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAVthbBAAAAA==",
                  category: "US",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD19.10",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAWthbBAAAAA==",
                  category: "XA",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD3.96",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAXthbBAAAAA==",
                  category: "XY",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD7.00",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAYthbBAAAAA==",
                  category: "YC",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD5.99",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAZthbBAAAAA==",
                  category: "E5",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD3.90",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
                {
                  taxDetail: [],
                  includedInBase: null,
                  key: "1Xb7KhBqWDKAathbBAAAAA==",
                  category: "YR",
                  carrierDefinedCategory: null,
                  segmentRef: null,
                  flightDetailsRef: null,
                  couponRef: null,
                  taxExempted: null,
                  providerCode: null,
                  supplierCode: null,
                  text: null,
                  amount: "USD245.00",
                  originAirport: null,
                  destinationAirport: null,
                  countryCode: null,
                  fareInfoRef: null,
                },
              ],
              fareCalc: "DAC TK X/IST TK NYC 450.00QF1PXOW NUC450.00END ROE1.0",
              passengerType: [
                {
                  name: null,
                  loyaltyCard: [],
                  discountCard: [],
                  personalGeography: null,
                  code: "ADT",
                  age: null,
                  dob: null,
                  gender: null,
                  pricePTCOnly: null,
                  bookingTravelerRef: null,
                  accompaniedPassenger: false,
                  residencyType: null,
                  fareGuaranteeInfo: null,
                },
              ],
              bookingTravelerRef: [],
              waiverCode: null,
              paymentRef: [],
              changePenalty: [
                {
                  amount: null,
                  percentage: "0.00",
                  penaltyApplies: "Anytime",
                  noShow: null,
                },
              ],
              cancelPenalty: [
                {
                  amount: "USD80.00",
                  percentage: null,
                  penaltyApplies: "Before Departure",
                  noShow: null,
                },
              ],
              noShowPenalty: [],
              mostRestrictivePenalties: null,
              feeInfo: [],
              adjustment: [],
              yield: [],
              airPricingModifiers: null,
              ticketingModifiersRef: [],
              airSegmentPricingModifiers: [],
              flightOptionsList: {
                flightOption: [
                  {
                    option: [
                      {
                        bookingInfo: [
                          {
                            bookingCode: "Q",
                            bookingCount: "9",
                            cabinClass: "Economy",
                            fareInfoRef: "1Xb7KhBqWDKANthbBAAAAA==",
                            segmentRef: "1Xb7KhBqWDKAdshbBAAAAA==",
                            couponRef: null,
                            airItinerarySolutionRef: null,
                            hostTokenRef: null,
                            taxInfoRef: null,
                          },
                          {
                            bookingCode: "Q",
                            bookingCount: "9",
                            cabinClass: "Economy",
                            fareInfoRef: "1Xb7KhBqWDKANthbBAAAAA==",
                            segmentRef: "1Xb7KhBqWDKAlshbBAAAAA==",
                            couponRef: null,
                            airItinerarySolutionRef: null,
                            hostTokenRef: null,
                            taxInfoRef: null,
                          },
                        ],
                        connection: [
                          {
                            fareNote: null,
                            changeOfPlane: false,
                            changeOfTerminal: false,
                            changeOfAirport: false,
                            stopOver: false,
                            minConnectionTime: null,
                            duration: null,
                            segmentIndex: 0,
                            flightDetailsIndex: null,
                            includeStopOverToFareQuote: null,
                          },
                        ],
                        key: "1Xb7KhBqWDKAbthbBAAAAA==",
                        travelTime: "P0DT20H55M0S",
                      },
                    ],
                    legRef: "1Xb7KhBqWDKA7shbBAAAAA==",
                    origin: "DAC",
                    destination: "NYC",
                  },
                ],
              },
              baggageAllowances: null,
              fareRulesFilter: null,
              policyCodesList: null,
              priceChange: [],
              actionDetails: null,
              commission: [],
              origin: null,
              destination: null,
              key: "1Xb7KhBqWDKAOthbBAAAAA==",
              commandKey: null,
              amountType: null,
              includesVAT: null,
              exchangeAmount: null,
              forfeitAmount: null,
              refundable: true,
              exchangeable: null,
              latestTicketingTime: "2021-07-15T23:59:00.000+06:00",
              pricingMethod: "GUARANTEED",
              checksum: null,
              platingCarrier: "TK",
              providerReservationInfoRef: null,
              airPricingInfoGroup: null,
              totalNetPrice: null,
              ticketed: null,
              pricingType: null,
              trueLastDateToTicket: null,
              fareCalculationInd: null,
              cat35Indicator: false,
              providerCode: "1G",
              supplierCode: null,
              totalPrice: "USD851.05",
              basePrice: "USD450.00",
              approximateTotalPrice: "USD851.05",
              approximateBasePrice: "USD450.00",
              equivalentBasePrice: null,
              taxes: "USD401.05",
              fees: null,
              services: null,
              approximateTaxes: null,
              approximateFees: null,
              inPolicy: null,
              preferredOption: null,
              elStat: null,
              keyOverride: null,
              eticketability: "YES",
            },
          ],
          airPricingResultMessage: [],
          feeInfo: [],
          fareNote: [],
          taxInfo: [],
          key: "1Xb7KhBqWDKAhthbBAAAAA==",
          completeItinerary: true,
          totalPrice: "USD851.05",
          basePrice: "USD450.00",
          approximateTotalPrice: "USD851.05",
          approximateBasePrice: "USD450.00",
          equivalentBasePrice: null,
          taxes: "USD401.05",
          fees: null,
          services: null,
          approximateTaxes: "USD401.05",
          approximateFees: null,
        },
      ],
      flightDetailsList: {
        "1Xb7KhBqWDKAkshbBAAAAA==": {
          connection: null,
          meals: [],
          inFlightServices: [],
          key: "1Xb7KhBqWDKAkshbBAAAAA==",
          equipment: "333",
          onTimePerformance: null,
          originTerminal: null,
          destinationTerminal: null,
          groundTime: null,
          automatedCheckin: false,
          origin: "IST",
          destination: "EWR",
          departureTime: "2021-07-15T18:20:00.000+03:00",
          arrivalTime: "2021-07-15T22:15:00.000-04:00",
          flightTime: 655,
          travelTime: 1550,
          distance: null,
          elStat: null,
          keyOverride: null,
        },
        "1Xb7KhBqWDKAishbBAAAAA==": {
          connection: null,
          meals: [],
          inFlightServices: [],
          key: "1Xb7KhBqWDKAishbBAAAAA==",
          equipment: "789",
          onTimePerformance: null,
          originTerminal: null,
          destinationTerminal: "1",
          groundTime: null,
          automatedCheckin: false,
          origin: "IST",
          destination: "JFK",
          departureTime: "2021-07-16T07:25:00.000+03:00",
          arrivalTime: "2021-07-16T10:50:00.000-04:00",
          flightTime: 625,
          travelTime: 2305,
          distance: null,
          elStat: null,
          keyOverride: null,
        },
        "1Xb7KhBqWDKAeshbBAAAAA==": {
          connection: null,
          meals: [],
          inFlightServices: [],
          key: "1Xb7KhBqWDKAeshbBAAAAA==",
          equipment: "333",
          onTimePerformance: null,
          originTerminal: null,
          destinationTerminal: null,
          groundTime: null,
          automatedCheckin: false,
          origin: "DAC",
          destination: "IST",
          departureTime: "2021-07-15T06:25:00.000+06:00",
          arrivalTime: "2021-07-15T11:55:00.000+03:00",
          flightTime: 510,
          travelTime: 1565,
          distance: null,
          elStat: null,
          keyOverride: null,
        },
        "1Xb7KhBqWDKAgshbBAAAAA==": {
          connection: null,
          meals: [],
          inFlightServices: [],
          key: "1Xb7KhBqWDKAgshbBAAAAA==",
          equipment: "789",
          onTimePerformance: null,
          originTerminal: null,
          destinationTerminal: "1",
          groundTime: null,
          automatedCheckin: false,
          origin: "IST",
          destination: "JFK",
          departureTime: "2021-07-15T18:35:00.000+03:00",
          arrivalTime: "2021-07-15T22:30:00.000-04:00",
          flightTime: 655,
          travelTime: 1565,
          distance: null,
          elStat: null,
          keyOverride: null,
        },
        "1Xb7KhBqWDKAmshbBAAAAA==": {
          connection: null,
          meals: [],
          inFlightServices: [],
          key: "1Xb7KhBqWDKAmshbBAAAAA==",
          equipment: "77W",
          onTimePerformance: null,
          originTerminal: null,
          destinationTerminal: "1",
          groundTime: null,
          automatedCheckin: false,
          origin: "IST",
          destination: "JFK",
          departureTime: "2021-07-15T13:30:00.000+03:00",
          arrivalTime: "2021-07-15T17:20:00.000-04:00",
          flightTime: 650,
          travelTime: 1255,
          distance: null,
          elStat: null,
          keyOverride: null,
        },
      },
      fareInfos: {
        "1Xb7KhBqWDKA8shbBAAAAA==": {
          fareTicketDesignator: [],
          ticketingCode: [],
          fareSurcharge: [],
          accountCode: [],
          contractCode: [],
          endorsement: [],
          baggageAllowance: {
            numberOfPieces: 3,
            maxWeight: {
              value: 15,
              unit: "KG",
            },
          },
          fareRuleKey: {
            value:
              "gws-eJxNjsEKAyEMRD9mmXviau1RUfdSsEuxuHvp/39GY9xCAzGjb5gYQjBkmFZjw38t+CztgfpOQIWRLv2F9eaIwHI7QUSMtpn9eHZohmcnpCqdk9WXfXIyUPxmJxqFU88ck7AZrJFjM4aUB/xEbCJrzG0vhxUX0d32i5GH/PQLonMr3A==",
            fareInfoRef: "1Xb7KhBqWDKA8shbBAAAAA==",
            providerCode: "1G",
          },
          fareRuleFailureInfo: null,
          fareRemarkRef: [],
          brand: {
            title: [],
            text: [],
            imageLocation: [],
            optionalServices: null,
            rules: [],
            serviceAssociations: null,
            upsellBrand: null,
            applicableSegment: [],
            defaultBrandDetail: [],
            key: "1Xb7KhBqWDKAlthbBAAAAA==",
            brandID: null,
            name: null,
            airItineraryDetailsRef: null,
            upSellBrandID: null,
            brandFound: false,
            upSellBrandFound: null,
            brandedDetailsAvailable: null,
            carrier: null,
            brandTier: null,
            brandMaintained: null,
          },
          commission: null,
          fareAttributes: null,
          changePenalty: null,
          cancelPenalty: null,
          fareRulesFilter: null,
          key: "1Xb7KhBqWDKA8shbBAAAAA==",
          fareBasis: "TF2PXOW",
          passengerTypeCode: "ADT",
          origin: "DAC",
          destination: "EWR",
          effectiveDate: "2021-03-24T15:16:00.000+06:00",
          travelDate: null,
          departureDate: "2021-07-14T18:00:00.000+00:00",
          amount: "USD365.00",
          privateFare: null,
          negotiatedFare: false,
          tourCode: null,
          waiverCode: null,
          notValidBefore: "2021-07-14T18:00:00.000+00:00",
          notValidAfter: "2021-07-14T18:00:00.000+00:00",
          pseudoCityCode: null,
          fareFamily: null,
          promotionalFare: null,
          carCode: null,
          valueCode: null,
          bulkTicket: null,
          inclusiveTour: null,
          value: null,
          supplierCode: null,
          taxAmount: null,
          elStat: null,
          keyOverride: null,
        },
        "1Xb7KhBqWDKANthbBAAAAA==": {
          fareTicketDesignator: [],
          ticketingCode: [],
          fareSurcharge: [],
          accountCode: [],
          contractCode: [],
          endorsement: [],
          baggageAllowance: {
            numberOfPieces: 3,
            maxWeight: {
              value: 25,
              unit: "KG",
            },
          },
          fareRuleKey: {
            value:
              "gws-eJxNjsEKxCAMRD+mzD1xFXtUtB62YLvg0vay//8ZG+MWNhAz+oaJIQRDhulhbPivCZ+prajvBFQY6WdZYR0RgeV2QRTjVXg/twOa4dkJqUrHZPVln5wMLL7YgXrh0jPHJGwEa2TfjC7lAbeITWSNue3LacVFNNvjx8hDfvoFkGQruw==",
            fareInfoRef: "1Xb7KhBqWDKANthbBAAAAA==",
            providerCode: "1G",
          },
          fareRuleFailureInfo: null,
          fareRemarkRef: [],
          brand: {
            title: [],
            text: [],
            imageLocation: [],
            optionalServices: null,
            rules: [],
            serviceAssociations: null,
            upsellBrand: null,
            applicableSegment: [],
            defaultBrandDetail: [],
            key: "1Xb7KhBqWDKAnthbBAAAAA==",
            brandID: null,
            name: null,
            airItineraryDetailsRef: null,
            upSellBrandID: null,
            brandFound: false,
            upSellBrandFound: null,
            brandedDetailsAvailable: null,
            carrier: null,
            brandTier: null,
            brandMaintained: null,
          },
          commission: null,
          fareAttributes: null,
          changePenalty: null,
          cancelPenalty: null,
          fareRulesFilter: null,
          key: "1Xb7KhBqWDKANthbBAAAAA==",
          fareBasis: "QF1PXOW",
          passengerTypeCode: "ADT",
          origin: "DAC",
          destination: "JFK",
          effectiveDate: "2021-03-24T15:16:00.000+06:00",
          travelDate: null,
          departureDate: "2021-07-14T18:00:00.000+00:00",
          amount: "USD450.00",
          privateFare: null,
          negotiatedFare: false,
          tourCode: null,
          waiverCode: null,
          notValidBefore: "2021-07-14T18:00:00.000+00:00",
          notValidAfter: "2021-07-14T18:00:00.000+00:00",
          pseudoCityCode: null,
          fareFamily: null,
          promotionalFare: null,
          carCode: null,
          valueCode: null,
          bulkTicket: null,
          inclusiveTour: null,
          value: null,
          supplierCode: null,
          taxAmount: null,
          elStat: null,
          keyOverride: null,
        },
        "1Xb7KhBqWDKAnshbBAAAAA==": {
          fareTicketDesignator: [],
          ticketingCode: [],
          fareSurcharge: [],
          accountCode: [],
          contractCode: [],
          endorsement: [],
          baggageAllowance: {
            numberOfPieces: 3,
            maxWeight: {
              value: null,
              unit: null,
            },
          },
          fareRuleKey: {
            value:
              "gws-eJxNjrEOwyAMRD8mut0mEDqCIAyNRDJQJVn6/59RY1qplowP3ulMCMGQYZqNDf814T21DfWVgAoj/Swb5sURgeV2g4gYrZjj2k9ohmcnpCodk9WXfXIysPpiB+qFW88ck7ARrJF9M7qUB/xEbCJrzO1YLysuooc9v4w85KcflsUryQ==",
            fareInfoRef: "1Xb7KhBqWDKAnshbBAAAAA==",
            providerCode: "1G",
          },
          fareRuleFailureInfo: null,
          fareRemarkRef: [],
          brand: {
            title: [],
            text: [],
            imageLocation: [],
            optionalServices: null,
            rules: [],
            serviceAssociations: null,
            upsellBrand: null,
            applicableSegment: [],
            defaultBrandDetail: [],
            key: "1Xb7KhBqWDKAjthbBAAAAA==",
            brandID: null,
            name: null,
            airItineraryDetailsRef: null,
            upSellBrandID: null,
            brandFound: false,
            upSellBrandFound: null,
            brandedDetailsAvailable: null,
            carrier: null,
            brandTier: null,
            brandMaintained: null,
          },
          commission: null,
          fareAttributes: null,
          changePenalty: null,
          cancelPenalty: null,
          fareRulesFilter: null,
          key: "1Xb7KhBqWDKAnshbBAAAAA==",
          fareBasis: "TF2PXOW",
          passengerTypeCode: "ADT",
          origin: "DAC",
          destination: "JFK",
          effectiveDate: "2021-03-24T15:16:00.000+06:00",
          travelDate: null,
          departureDate: "2021-07-14T18:00:00.000+00:00",
          amount: "USD365.00",
          privateFare: null,
          negotiatedFare: false,
          tourCode: null,
          waiverCode: null,
          notValidBefore: "2021-07-14T18:00:00.000+00:00",
          notValidAfter: "2021-07-14T18:00:00.000+00:00",
          pseudoCityCode: null,
          fareFamily: null,
          promotionalFare: null,
          carCode: null,
          valueCode: null,
          bulkTicket: null,
          inclusiveTour: null,
          value: null,
          supplierCode: null,
          taxAmount: null,
          elStat: null,
          keyOverride: null,
        },
      },
      hostTokenList: null,
      airSegments: {
        "1Xb7KhBqWDKAjshbBAAAAA==": {
          segmentRemark: [],
          key: "1Xb7KhBqWDKAjshbBAAAAA==",
          status: null,
          passive: null,
          travelOrder: null,
          providerSegmentOrder: null,
          elStat: null,
          keyOverride: null,
          sponsoredFltInfo: null,
          codeshareInfo: null,
          airAvailInfo: [
            {
              bookingCodeInfo: [],
              fareTokenInfo: [],
              providerCode: "1G",
              hostTokenRef: null,
            },
          ],
          flightDetails: [],
          flightDetailsRef: [
            {
              key: "1Xb7KhBqWDKAkshbBAAAAA==",
            },
          ],
          alternateLocationDistanceRef: [],
          connection: null,
          sellMessage: [],
          railCoachDetails: [],
          openSegment: null,
          group: 0,
          carrier: "TK",
          cabinClass: null,
          flightNumber: "29",
          classOfService: null,
          equipment: "333",
          marriageGroup: null,
          numberOfStops: null,
          seamless: null,
          changeOfPlane: false,
          guaranteedPaymentCarrier: null,
          hostTokenRef: null,
          providerReservationInfoRef: null,
          passiveProviderReservationInfoRef: null,
          optionalServicesIndicator: false,
          availabilitySource: "S",
          blackListed: null,
          operationalStatus: null,
          numberInParty: null,
          railCoachNumber: null,
          bookingDate: null,
          flownSegment: false,
          scheduleChange: false,
          brandIndicator: null,
          providerCode: null,
          supplierCode: null,
          origin: "IST",
          destination: "EWR",
          departureTime: "2021-07-15T18:20:00.000+03:00",
          arrivalTime: "2021-07-15T22:15:00.000-04:00",
          flightTime: 655,
          travelTime: null,
          distance: 5002,
          participantLevel: "Secure Sell",
          linkAvailability: true,
          polledAvailabilityOption: "Polled avail used",
          availabilityDisplayType: "Fare Shop/Optimal Shop",
          apisrequirementsRef: null,
          eticketability: "YES",
        },
        "1Xb7KhBqWDKAdshbBAAAAA==": {
          segmentRemark: [],
          key: "1Xb7KhBqWDKAdshbBAAAAA==",
          status: null,
          passive: null,
          travelOrder: null,
          providerSegmentOrder: null,
          elStat: null,
          keyOverride: null,
          sponsoredFltInfo: null,
          codeshareInfo: null,
          airAvailInfo: [
            {
              bookingCodeInfo: [],
              fareTokenInfo: [],
              providerCode: "1G",
              hostTokenRef: null,
            },
          ],
          flightDetails: [],
          flightDetailsRef: [
            {
              key: "1Xb7KhBqWDKAeshbBAAAAA==",
            },
          ],
          alternateLocationDistanceRef: [],
          connection: null,
          sellMessage: [],
          railCoachDetails: [],
          openSegment: null,
          group: 0,
          carrier: "TK",
          cabinClass: null,
          flightNumber: "713",
          classOfService: null,
          equipment: "333",
          marriageGroup: null,
          numberOfStops: null,
          seamless: null,
          changeOfPlane: false,
          guaranteedPaymentCarrier: null,
          hostTokenRef: null,
          providerReservationInfoRef: null,
          passiveProviderReservationInfoRef: null,
          optionalServicesIndicator: false,
          availabilitySource: "S",
          blackListed: null,
          operationalStatus: null,
          numberInParty: null,
          railCoachNumber: null,
          bookingDate: null,
          flownSegment: false,
          scheduleChange: false,
          brandIndicator: null,
          providerCode: null,
          supplierCode: null,
          origin: "DAC",
          destination: "IST",
          departureTime: "2021-07-15T06:25:00.000+06:00",
          arrivalTime: "2021-07-15T11:55:00.000+03:00",
          flightTime: 510,
          travelTime: null,
          distance: 3698,
          participantLevel: "Secure Sell",
          linkAvailability: true,
          polledAvailabilityOption: "Polled avail used",
          availabilityDisplayType: "Fare Shop/Optimal Shop",
          apisrequirementsRef: null,
          eticketability: "YES",
        },
        "1Xb7KhBqWDKAlshbBAAAAA==": {
          segmentRemark: [],
          key: "1Xb7KhBqWDKAlshbBAAAAA==",
          status: null,
          passive: null,
          travelOrder: null,
          providerSegmentOrder: null,
          elStat: null,
          keyOverride: null,
          sponsoredFltInfo: null,
          codeshareInfo: null,
          airAvailInfo: [
            {
              bookingCodeInfo: [],
              fareTokenInfo: [],
              providerCode: "1G",
              hostTokenRef: null,
            },
          ],
          flightDetails: [],
          flightDetailsRef: [
            {
              key: "1Xb7KhBqWDKAmshbBAAAAA==",
            },
          ],
          alternateLocationDistanceRef: [],
          connection: null,
          sellMessage: [],
          railCoachDetails: [],
          openSegment: null,
          group: 0,
          carrier: "TK",
          cabinClass: null,
          flightNumber: "1",
          classOfService: null,
          equipment: "77W",
          marriageGroup: null,
          numberOfStops: null,
          seamless: null,
          changeOfPlane: false,
          guaranteedPaymentCarrier: null,
          hostTokenRef: null,
          providerReservationInfoRef: null,
          passiveProviderReservationInfoRef: null,
          optionalServicesIndicator: false,
          availabilitySource: "S",
          blackListed: null,
          operationalStatus: null,
          numberInParty: null,
          railCoachNumber: null,
          bookingDate: null,
          flownSegment: false,
          scheduleChange: false,
          brandIndicator: null,
          providerCode: null,
          supplierCode: null,
          origin: "IST",
          destination: "JFK",
          departureTime: "2021-07-15T13:30:00.000+03:00",
          arrivalTime: "2021-07-15T17:20:00.000-04:00",
          flightTime: 650,
          travelTime: null,
          distance: 5002,
          participantLevel: "Secure Sell",
          linkAvailability: true,
          polledAvailabilityOption: "Polled avail used",
          availabilityDisplayType: "Fare Shop/Optimal Shop",
          apisrequirementsRef: null,
          eticketability: "YES",
        },
        "1Xb7KhBqWDKAhshbBAAAAA==": {
          segmentRemark: [],
          key: "1Xb7KhBqWDKAhshbBAAAAA==",
          status: null,
          passive: null,
          travelOrder: null,
          providerSegmentOrder: null,
          elStat: null,
          keyOverride: null,
          sponsoredFltInfo: null,
          codeshareInfo: null,
          airAvailInfo: [
            {
              bookingCodeInfo: [],
              fareTokenInfo: [],
              providerCode: "1G",
              hostTokenRef: null,
            },
          ],
          flightDetails: [],
          flightDetailsRef: [
            {
              key: "1Xb7KhBqWDKAishbBAAAAA==",
            },
          ],
          alternateLocationDistanceRef: [],
          connection: null,
          sellMessage: [],
          railCoachDetails: [],
          openSegment: null,
          group: 0,
          carrier: "TK",
          cabinClass: null,
          flightNumber: "3",
          classOfService: null,
          equipment: "789",
          marriageGroup: null,
          numberOfStops: null,
          seamless: null,
          changeOfPlane: false,
          guaranteedPaymentCarrier: null,
          hostTokenRef: null,
          providerReservationInfoRef: null,
          passiveProviderReservationInfoRef: null,
          optionalServicesIndicator: false,
          availabilitySource: "S",
          blackListed: null,
          operationalStatus: null,
          numberInParty: null,
          railCoachNumber: null,
          bookingDate: null,
          flownSegment: false,
          scheduleChange: false,
          brandIndicator: null,
          providerCode: null,
          supplierCode: null,
          origin: "IST",
          destination: "JFK",
          departureTime: "2021-07-16T07:25:00.000+03:00",
          arrivalTime: "2021-07-16T10:50:00.000-04:00",
          flightTime: 625,
          travelTime: null,
          distance: 5002,
          participantLevel: "Secure Sell",
          linkAvailability: true,
          polledAvailabilityOption: "Polled avail used",
          availabilityDisplayType: "Fare Shop/Optimal Shop",
          apisrequirementsRef: null,
          eticketability: "YES",
        },
        "1Xb7KhBqWDKAfshbBAAAAA==": {
          segmentRemark: [],
          key: "1Xb7KhBqWDKAfshbBAAAAA==",
          status: null,
          passive: null,
          travelOrder: null,
          providerSegmentOrder: null,
          elStat: null,
          keyOverride: null,
          sponsoredFltInfo: null,
          codeshareInfo: null,
          airAvailInfo: [
            {
              bookingCodeInfo: [],
              fareTokenInfo: [],
              providerCode: "1G",
              hostTokenRef: null,
            },
          ],
          flightDetails: [],
          flightDetailsRef: [
            {
              key: "1Xb7KhBqWDKAgshbBAAAAA==",
            },
          ],
          alternateLocationDistanceRef: [],
          connection: null,
          sellMessage: [],
          railCoachDetails: [],
          openSegment: null,
          group: 0,
          carrier: "TK",
          cabinClass: null,
          flightNumber: "11",
          classOfService: null,
          equipment: "789",
          marriageGroup: null,
          numberOfStops: null,
          seamless: null,
          changeOfPlane: false,
          guaranteedPaymentCarrier: null,
          hostTokenRef: null,
          providerReservationInfoRef: null,
          passiveProviderReservationInfoRef: null,
          optionalServicesIndicator: false,
          availabilitySource: "S",
          blackListed: null,
          operationalStatus: null,
          numberInParty: null,
          railCoachNumber: null,
          bookingDate: null,
          flownSegment: false,
          scheduleChange: false,
          brandIndicator: null,
          providerCode: null,
          supplierCode: null,
          origin: "IST",
          destination: "JFK",
          departureTime: "2021-07-15T18:35:00.000+03:00",
          arrivalTime: "2021-07-15T22:30:00.000-04:00",
          flightTime: 655,
          travelTime: null,
          distance: 5002,
          participantLevel: "Secure Sell",
          linkAvailability: true,
          polledAvailabilityOption: "Polled avail used",
          availabilityDisplayType: "Fare Shop/Optimal Shop",
          apisrequirementsRef: null,
          eticketability: "YES",
        },
      },
    },
    flights: [],
  };

  componentDidMount() {
    this.getFlights();
  }

  getFlights = () => {
    let {
      responseMessage,
      flightDetailsList,
      airSegments,
      routeList,
      airPricePoints,
      fareInfos
    } = this.state.result;

    const localFlights = [];

    airPricePoints &&
      airPricePoints.forEach((airPrice) => {
        let {
          approximateFees,
          approximateTaxes,
          approximateTotalPrice,
          basePrice,
          taxes,
          totalPrice,
          approximateBasePrice,
        } = airPrice;
        let priceInfos = {
          approximateFees,
          approximateTaxes,
          approximateTotalPrice,
          basePrice,
          taxes,
          totalPrice,
          approximateBasePrice,
        };

        airPrice &&
          airPrice.airPricingInfo &&
          airPrice.airPricingInfo.forEach((pricingInfo) => {
            let { cancelPenalty, changePenalty } = pricingInfo;

            pricingInfo &&
              pricingInfo.flightOptionsList &&
              pricingInfo.flightOptionsList.flightOption &&
              pricingInfo.flightOptionsList.flightOption.forEach(
                (flightOpt) => {
                  let { origin, destination } = flightOpt;
                  flightOpt &&
                    flightOpt.option &&
                    flightOpt.option.forEach((option) => {
                      localFlights.push({
                        priceInfos,
                        origin,
                        destination,
                        cancelPenalty,
                        changePenalty,
                        option,
                      });
                    });
                }
              );
          });
      });

    
    //this.setState({flights:localFlights});
  };
  render() {
    let {
      responseMessage,
      flightDetailsList,
      airSegments,
      fareInfos,
      routeList,
      airPricePoints,
    } = this.state.result;

    let count = 0;
    return (
      <React.Fragment>
        {airPricePoints &&
          airPricePoints.map((airPrice, idx) => {
            let {
              approximateFees,
              approximateTaxes,
              approximateTotalPrice,
              basePrice,
              taxes,
              totalPrice,
              approximateBasePrice,
            } = airPrice;
            let priceInfos = {
              approximateFees,
              approximateTaxes,
              approximateTotalPrice,
              basePrice,
              taxes,
              totalPrice,
              approximateBasePrice,
            };
            return (
              <React.Fragment key={`price-idx-${idx}`}>
                {airPrice &&
                  airPrice.airPricingInfo &&
                  airPrice.airPricingInfo.map((pricingInfo, pIdx) => {
                    console.log("pricingInfo, ", pricingInfo);
                    let { cancelPenalty, changePenalty, passengerType } = pricingInfo;
                  
                    let cancel = {type:passengerType[0]&&passengerType[0].code, penalty:cancelPenalty};
                    let change = {type:passengerType[0]&&passengerType[0].code, penalty:changePenalty};
                    return (
                      <React.Fragment key={`priceing-idx-${idx}`}>
                        {pricingInfo &&
                          pricingInfo.flightOptionsList &&
                          pricingInfo.flightOptionsList.flightOption &&
                          pricingInfo.flightOptionsList.flightOption.map(
                            (flightOpt, idx) => {
                              return (
                                <React.Fragment
                                  key={`flightOptions-idx-${idx}`}
                                >
                                  {flightOpt &&
                                    flightOpt.option &&
                                    flightOpt.option.map((option, ibx) => {
                                      return (
                                        <React.Fragment key={`owcr-${ibx}`}>
                                          <OneWayFlightCard
                                            id={ibx}
                                            option={option}
                                            origin={flightOpt.origin}
                                            destination={flightOpt.destination}
                                            approximateBasePrice={
                                              airPrice.approximateBasePrice
                                            }
                                            airPriceInfos={priceInfos}
                                            cancelPenalty={cancel}
                                            changePenalty={change}
                                            airSegments={airSegments}
                                            flightsDetails={flightDetailsList}
                                            fareInfos={fareInfos}
                                          />
                                        </React.Fragment>
                                      );
                                    })}
                                </React.Fragment>
                              );
                            }
                          )}
                      </React.Fragment>
                    );
                  })}
              </React.Fragment>
            );
          })}
      </React.Fragment>
    );
  }
}

export default OneWaySearchResult;
